sudo: false
language: python
services:
- "docker"
env:
  global:
  - secure: laKPriZCfuRz9A1FPIydxWXn/ZKLMhpfEM+r149wIpDj1mFzS9Rm8oT++FQyENmiyn30NUkK88bvAEMn+JYTuXMZbrmYP1Fgmuy6/Dn6VRV0EEI3ZpD+7ZDutwx4/yYectLK4Bsc6zP1XnjOkOnlsVm9u5DPYKqJB+V63llZ4WcsQhslCJ55HV5M2QpHLjssvBryhp0HvvhhileqPI7uaqRixdudb5GTxiqpLPe//2vLqpV3HgtphikvCIq/yWSgR1w0L7XBv3cGX3BrK5BIHEwsY99dnAp7719SS1StgdcVkMmydNMMlsM39roHNsRQijmhMfonBwQsQgl9LbW07+x9LAnoCDpGbfSfq/ckOB7USDUcb2AmehK6ennSiGXBv+8zrl0q5P1hNrG3IcqwHJLnCOnOaYZLWOFUy0LeSMxVOO0E8n93uvU/fSvsPWIyDjfKndoq1P1c+S0nIQCGh7Yz9eWq5IWOC4XHhFLgQTjmx+0HKiENjYtXjHZy5wS0oZRoAny7s2+v7fMsUQlnf6Lsoden+rTBXtRN2drvsOSWM4iVmCpZ2M+xoiGhP24zTaRBxgYpJvZN/YNXHT4/IA8iDSTQCbNA/hmXlzhnFi2MvxGrm3UslVDqkOJ2+uhqmQIReXH5/AHCz/n4+DqEPBYB+Xk1hycLV5TlbQZKahc=
  - secure: SAnY0Fbk+4HLoOnbDbHEd88T+qfedKpes8fFyY6mmNm3pB6JzIYg6wyhDvJgk4E/z6ZnpNDp7T/24DUROgH2mPtZjj8WcjPVyAVH2xepPPvT09ToH6nJ1/IPynl34Mc9u/jnsTRwX5jCPJBe4DOUBkOV7JU+/UGiGg0kOS4WVAzxolyqtasZg/MS2PsKupWNBzPgcBz1IlUsc8+ctomM+iXdKCQ+9a/0HFfGau5cWsMUW65PeYPfGnzHUNG3vDRursmfvIlQcl9lo49RLFu95w5vv4ftp7LGFxE8hhE6MdoyyCiLQc/yj+4KbWDaQeMbJdkrwEl1KvkoDe1B1S5OlI6KR4aTkJ13BmdlQoSHnh/l/Igh9Y/1fGpn7R8DF86dhpTjPjnJLrp8Pf0yOrRCCgCUMUWHbaV0P/XdVMV1F9aVhkest1dDOcBWv0dUWwNrqARtxhv0318WnkKfJUAqiZ6QeBrzi+F20l3+CM2FZIqaOyt8XecEamcw6BCI7wMl2/sCyAruUSFyAr3Dn0kwZE0Qrjs4+/KItpiqa9KYQJpElTGCZb69oDiaa1l30lrFA7yJMXKIpJxQ633/NmkREI3ZJiNmuZztNOV0iOUva+vTdxtatEbYz6PUAzl9FE1Jg80h26pCtuuws7NqGvUJbO+pvddFOp7orLwk5grAtic=
  matrix:
  - PG_VERSION=10.7
install:
- pip install awscli
script:
- make build postgresql_version=${PG_VERSION}
deploy:
- provider: script
  skip_cleanup: true
  script:
  - make deploy list postgresql_version=${PG_VERSION} region=us-west-2 layer_name=postgresql-libpq-ssl-dev
  on:
    branch: dev
    condition: ${PG_VERSION} = 10.7
- provider: script
  skip_cleanup: true
  script:
  - make deploy list postgresql_version=${PG_VERSION} region=us-west-2 layer_name=postgresql-libpq-ssl
  on:
    branch: master
    condition: ${PG_VERSION} = 10.7
